version: '3.8'

services:
  frontend-router-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # WebSocket server port
      - "8081:8081"  # MCP server port
    restart: unless-stopped
    # Optional: Add environment variables if needed
    # environment:
    #   - KEY=value
    volumes:
      - ./logs:/app/logs  # Optional: mount logs directory
