global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'frontend-router-mcp'
    static_configs:
      - targets: ['localhost:8082']
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s
    scheme: http
    
  - job_name: 'frontend-router-mcp-health'
    static_configs:
      - targets: ['localhost:8082']
    metrics_path: /health
    scrape_interval: 30s
    scrape_timeout: 10s
    scheme: http
    
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093